version: "2"

services:

  hello:
    image: thepixelmonsterzapp/hello
    build: ./hello
    environment:
      USE_IP_ADDR: "1"
      ENV: "DEV"
    ports: [ "0.0.0.0:9090:9090" ]

  monsterz-den:
    image: thepixelmonsterzapp/monsterz-den
    build: ./monsterz-den

  redis:
    image: redis:3
