version: "2"

services:

  weavescope:
    image: "weaveworks/scope:0.14.0"
    restart: "always"
    network_mode: "host"
    pid: "host"
    privileged: true
    labels: [ "works.weave.role=system" ]
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock:rw" ]
    command: [ "--probe.docker=true" ]
